import type { Question, SIECategory } from "@/types";

function q(
  id: string,
  category: SIECategory,
  question: string,
  choices: [string, string, string, string],
  correctIndex: 0 | 1 | 2 | 3,
  explanation: string,
): Question {
  const list = [choices[0], choices[1], choices[2], choices[3]];
  return {
    id,
    category,
    question,
    choices: list,
    correctAnswer: choices[correctIndex],
    explanation,
  };
}

export const questions: Question[] = [
  q(
    "sie-001",
    "Securities Products",
    "Which statement best describes common stock?",
    [
      "It pays a fixed dividend that never changes.",
      "It represents ownership in a corporation and typically carries voting rights.",
      "It always matures at par on a stated date.",
      "It is senior to all bonds in a liquidation.",
    ],
    1,
    "Common stock represents equity ownership. Dividends are not fixed, there is no maturity date, and common shareholders are behind debt holders in liquidation.",
  ),
  q(
    "sie-002",
    "Securities Products",
    "A corporate bond is best described as:",
    [
      "An equity interest with voting rights.",
      "A loan to the issuer with scheduled interest and return of principal at maturity.",
      "A derivative whose payoff is based on an index.",
      "A demand deposit at a broker-dealer.",
    ],
    1,
    "Bondholders lend money to the issuer, receive interest (coupon) payments, and expect principal repayment according to the indenture.",
  ),
  q(
    "sie-003",
    "Securities Products",
    "Interest on many municipal bonds may be advantageous to certain investors primarily because:",
    [
      "Municipal bonds are always exempt from federal, state, and local tax for every investor.",
      "Some municipal interest can be exempt from federal income tax (and sometimes state/local tax if the investor lives in the issuing state).",
      "Municipal bonds always trade without credit risk.",
      "Municipal bonds pay higher coupons than Treasuries with the same maturity.",
    ],
    1,
    "A key feature is potential tax treatment of interest. Exemptions depend on the bond, the investor’s residency, and applicable law—not all munis are tax-free for everyone.",
  ),
  q(
    "sie-004",
    "Securities Products",
    "A limited partner in a direct participation program (DPP) generally:",
    [
      "Has unlimited personal liability for partnership debts.",
      "Participates in management and daily operations by default.",
      "Has liability limited to the amount invested (assuming typical LP structures).",
      "Is always registered as a broker-dealer.",
    ],
    2,
    "Limited partners typically have limited liability up to their investment and do not manage the program; the general partner manages operations.",
  ),
  q(
    "sie-005",
    "Securities Products",
    "An open-end management investment company (mutual fund) generally:",
    [
      "Issues a fixed number of shares that trade on an exchange like stock.",
      "Continuously issues and redeems shares at NAV (with possible sales loads or fees).",
      "Must hold at least 65% of assets in municipal bonds.",
      "Cannot employ a professional investment adviser.",
    ],
    1,
    "Open-end funds continuously offer and redeem shares. Pricing is typically tied to net asset value (NAV), subject to fund policies and fees.",
  ),
  q(
    "sie-006",
    "Customer Accounts",
    "A joint tenants with rights of survivorship (JTWROS) account typically means:",
    [
      "Each tenant owns a separate, divisible share that passes by will.",
      "Upon the death of one tenant, the decedent’s interest passes to the surviving tenant(s).",
      "Only corporations may open this account type.",
      "The account must use margin at all times.",
    ],
    1,
    "JTWROS includes a survivorship feature: the deceased joint tenant’s interest generally passes to the surviving joint tenant(s) by operation of law, not by will.",
  ),
  q(
    "sie-007",
    "Customer Accounts",
    "A registered representative recommending a security should consider:",
    [
      "Only the representative’s personal opinion about the market.",
      "The customer’s profile, including objectives, risk tolerance, time horizon, and financial situation.",
      "Only the issuer’s marketing materials.",
      "Only the security’s past performance with no other factors.",
    ],
    1,
    "Suitability and associated obligations generally require understanding the customer and whether a recommendation aligns with the customer’s profile and facts.",
  ),
  q(
    "sie-008",
    "Regulatory Rules",
    "A ‘retail communication’ is most accurately described as:",
    [
      "Any verbal conversation between two institutional traders.",
      "Written or electronic communications distributed or made available to more than 25 retail investors within any 30-calendar-day period (per regulatory definitions used in firm policies and rules frameworks).",
      "Only communications filed with the SEC by the issuer.",
      "Internal email between supervisors only.",
    ],
    1,
    "FINRA rules distinguish communication categories (e.g., retail vs. institutional) with specific thresholds and requirements; firms supervise and classify communications accordingly.",
  ),
  q(
    "sie-009",
    "Regulatory Rules",
    "A member firm’s AML program commonly includes:",
    [
      "Ignoring cash deposits under $10,000.",
      "Customer identification procedures, monitoring, and reporting suspicious activity as required.",
      "Approving all customer trades without documentation.",
      "Eliminating recordkeeping for wire transfers.",
    ],
    1,
    "AML programs include CIP/KYC elements, ongoing monitoring, and compliance with reporting obligations such as SAR/CTR requirements as applicable.",
  ),
  q(
    "sie-010",
    "Trading",
    "A market maker on an exchange most directly helps provide:",
    [
      "Guaranteed profits for all investors.",
      "Liquidity by quoting bids and offers.",
      "Federal insurance for customer accounts.",
      "Underwriting for all IPOs nationally.",
    ],
    1,
    "Market makers facilitate trading by standing ready to buy and sell, contributing to liquidity and tighter markets (subject to exchange rules).",
  ),
  q(
    "sie-011",
    "Customer Accounts",
    "Buying securities on margin means the customer:",
    [
      "Must pay the full purchase price in cash on settlement with no borrowing.",
      "Borrows funds from the broker-dealer, using securities as collateral, subject to Reg T and maintenance rules.",
      "Is prohibited from selling the securities later.",
      "Avoids all interest charges by definition.",
    ],
    1,
    "Margin involves borrowing from the broker, collateralizing the loan with securities, and meeting initial/maintenance requirements.",
  ),
  q(
    "sie-012",
    "Securities Products",
    "Buying a call option gives the holder:",
    [
      "The obligation to buy stock at the strike price.",
      "The right to buy the underlying at the strike price until expiration (for American-style), subject to premium paid.",
      "The right to sell the underlying at the strike price.",
      "A fixed dividend from the issuer.",
    ],
    1,
    "A call purchaser obtains the right (not obligation) to buy the underlying at the strike, in exchange for paying the premium.",
  ),
  q(
    "sie-013",
    "Securities Products",
    "A put option is in-the-money when:",
    [
      "The market price of the underlying is above the strike price.",
      "The market price of the underlying is below the strike price (for a standard equity put).",
      "The option has zero time value.",
      "The contract has expired.",
    ],
    1,
    "For a put, intrinsic value exists when the underlying is below the strike (simplified standard equity option framing).",
  ),
  q(
    "sie-014",
    "Capital Markets",
    "If interest rates rise, existing fixed-rate bond prices generally:",
    ["Rise.", "Fall.", "Remain unchanged.", "Move in a way unrelated to duration."],
    1,
    "Bond prices and yields move inversely: higher market yields typically reduce the market price of existing fixed-rate bonds.",
  ),
  q(
    "sie-015",
    "Capital Markets",
    "In a firm commitment underwriting, the underwriter:",
    [
      "Acts only as agent and returns unsold shares to the issuer.",
      "Purchases the issue from the issuer and resells it to the public, bearing distribution risk.",
      "Provides a best-efforts selling effort with no capital risk.",
      "Must be a municipal issuer.",
    ],
    1,
    "Firm commitment means the syndicate buys the securities from the issuer (subject to terms) and distributes them, taking on distribution risk.",
  ),
  q(
    "sie-016",
    "Trading",
    "A ‘limit order’ is an order to:",
    [
      "Execute immediately at the best available price with no price restriction.",
      "Buy or sell at a specified price or better.",
      "Execute only after the market closes.",
      "Cancel all other open orders automatically.",
    ],
    1,
    "Limit orders set a price constraint: buys execute at the limit or lower; sells at the limit or higher, subject to market conditions and availability.",
  ),
  q(
    "sie-017",
    "Trading",
    "A stop order becomes:",
    [
      "A market order once the stop price is triggered (typical behavior).",
      "A guarantee of execution at the stop price.",
      "An order that can never be elected.",
      "An order available only for bonds.",
    ],
    0,
    "Once elected/triggered, a stop order commonly becomes a market order; execution price can gap away from the stop level in volatile conditions.",
  ),
  q(
    "sie-018",
    "Regulatory Rules",
    "SIPC coverage is primarily associated with:",
    [
      "Insurance against market losses on stock investments.",
      "Protection of customer securities and cash at a failed broker-dealer within defined limits and rules.",
      "Guaranteeing bond issuers will not default.",
      "Covering losses from fraudulent tax filings.",
    ],
    1,
    "SIPC helps return customer assets when a broker-dealer fails, within statutory limits; it does not protect against market loss.",
  ),
  q(
    "sie-019",
    "Regulatory Rules",
    "Front-running a customer order generally refers to:",
    [
      "Executing a customer’s order promptly at the customer’s instruction.",
      "Trading ahead of a customer order on the same security for the firm’s or RR’s advantage.",
      "Providing a written disclosure at account opening.",
      "Using a limit order instead of a market order.",
    ],
    1,
    "Front-running involves improper trading ahead of a known customer order, creating conflicts and fairness concerns.",
  ),
  q(
    "sie-020",
    "Regulatory Rules",
    "FINRA is best described as:",
    [
      "A federal agency that insures bank deposits.",
      "A self-regulatory organization (SRO) that regulates member broker-dealers and associated persons.",
      "A stock exchange that lists only municipal bonds.",
      "An international central bank.",
    ],
    1,
    "FINRA is an SRO with rulemaking and enforcement authority over its member firms and registered individuals, subject to SEC oversight.",
  ),
  q(
    "sie-021",
    "Securities Products",
    "A stock split that increases the number of shares outstanding typically:",
    [
      "Increases the total market value of equity solely because of the split.",
      "Adjusts share count and price per share while leaving the investor’s proportional ownership unchanged (all else equal).",
      "Eliminates voting rights for common shareholders.",
      "Converts common stock into bonds automatically.",
    ],
    1,
    "Splits adjust share count and price; they do not inherently create value—ownership percentage remains the same absent other changes.",
  ),
  q(
    "sie-022",
    "Capital Markets",
    "Purchasing-power (inflation) risk most directly describes the risk that:",
    [
      "A bond issuer defaults on interest payments.",
      "The real value of money or returns may erode if inflation rises.",
      "A stock exchange halts trading in a security.",
      "Currency exchange rates remain fixed.",
    ],
    1,
    "Inflation can reduce purchasing power of future interest and principal repayments in real terms.",
  ),
  q(
    "sie-023",
    "Customer Accounts",
    "A cash account customer generally:",
    [
      "Must borrow from the broker to purchase securities.",
      "Pays in full for purchases by settlement without extension of credit by the broker for the purchase.",
      "Has unlimited leverage without disclosures.",
      "Cannot sell securities once purchased.",
    ],
    1,
    "In a cash account, purchases are paid in full without margin extension from the broker for those purchases (subject to firm policies and settlement).",
  ),
  q(
    "sie-024",
    "Capital Markets",
    "During an economic expansion, corporate earnings and employment often:",
    [
      "Decline consistently.",
      "Trend higher, though sectors can differ.",
      "Become unrelated to GDP.",
      "Force the Federal Reserve to eliminate all debt.",
    ],
    1,
    "Expansions are generally associated with growth in output, employment, and often earnings, though timing and magnitude vary.",
  ),
  q(
    "sie-025",
    "Securities Products",
    "A Treasury bill (T-bill) is typically issued:",
    [
      "With a stated coupon paid semiannually and a 30-year maturity.",
      "At a discount to maturity value with short-term maturities.",
      "Only by municipal issuers.",
      "As an equity security.",
    ],
    1,
    "T-bills are short-term government securities, commonly issued at a discount and maturing at par.",
  ),
  q(
    "sie-026",
    "Securities Products",
    "Diversification primarily aims to:",
    [
      "Eliminate all investment risk.",
      "Reduce unsystematic risk by spreading investments across instruments or sectors.",
      "Guarantee returns equal to the market index.",
      "Convert all holdings to cash automatically.",
    ],
    1,
    "Diversification can reduce company-specific risk, but market-wide (systematic) risk remains.",
  ),
  q(
    "sie-027",
    "Regulatory Rules",
    "A ‘Chinese wall’ (information barrier) is used to:",
    [
      "Prevent all employees from communicating.",
      "Limit the flow of material nonpublic information between departments such as investment banking and trading.",
      "Replace written supervisory procedures.",
      "Eliminate the need for disclosures.",
    ],
    1,
    "Information barriers help prevent misuse of confidential information across areas of a firm.",
  ),
  q(
    "sie-028",
    "Capital Markets",
    "A preliminary prospectus (often called a ‘red herring’) may be distributed:",
    [
      "Only after the registration statement is effective and the final prospectus is delivered.",
      "During the waiting period with required disclosures, subject to rules and contents.",
      "Without any risk disclosures.",
      "Exclusively to non-accredited investors only.",
    ],
    1,
    "The preliminary prospectus is used in the pre-effective period with required legend/disclosures; sales constraints apply until effectiveness and prospectus delivery rules are met.",
  ),
  q(
    "sie-029",
    "Regulatory Rules",
    "Regulation Best Interest (Reg BI) applies to:",
    [
      "Only municipal advisors.",
      "Broker-dealers and associated persons when making recommendations to retail customers, subject to the rule’s requirements.",
      "Only investment advisers registered at the state level.",
      "Only trading on foreign exchanges.",
    ],
    1,
    "Reg BI establishes a standard of conduct for broker-dealers/reps when recommending securities or strategies to retail customers.",
  ),
  q(
    "sie-030",
    "Trading",
    "For many standard corporate stock trades in the U.S., settlement is commonly:",
    [
      "Same day (T+0) for all transactions without exception.",
      "T+1 business day for many cash market trades (subject to product and market practice).",
      "T+30 calendar days for all equities.",
      "Only on weekends.",
    ],
    1,
    "U.S. equities moved toward shorter settlement cycles; industry practice has been T+1 for many routine equity transactions (confirm current rules for your exam prep provider).",
  ),
];
